### PR TITLE
Our local fixes to your plugin

### PR DESCRIPTION
**Pull request by tlock**
Hi,

Our local fixes to your plugin after you recent Moodle 2.5 release.

Regards,
Tim

### CODE REVIEW

**Comment by tlock** [comment]
I've added indexes for scalability.

**Comment by tlock** [comment]
Added additional changes.

**Comment by thanhtri** [comment]
Thank you so much Tim, I am merging and retesting.
Sorry for not being responsive. I was consumed with another project!

I also plan to rewrite the code quite subtantially with a more object oriented style and conform more to  Moodle style. However, it could take more time.

**Comment by thanhtri** [comment]
I hesitated a bit to move the report directory to temp directory, since the word temporary means that it is used once and could be deleted with no harm. So, the temporarily extracted files is placed in $CFG->tempdir/plagiarism_programming/ while the report directory is placed in $CFG->dataroot/plagiarism_report/. Anyway, I think you have more experience of managing the server than me.

**Comment by thanhtri** [comment]
I wonder whether it's good to check sesskey in all ajax requests, not just in course settings? This may be good practice, but javascript need to handle the error when the sesskey failed. Otherwise, the page doesn't move when sesskey does not match.

**Comment by thanhtri** [comment]
Hi Tim,

I think there is something (likely a bug with Moodle 2.5). These files are in mod/assign/
- In locallib.php, line 3946 function render_area_files -> return $this->get_renderer()->assign_files($this->context, $submissionid, $area, $component);
- In renderer.php, line 48 function return $this->render(new assign_files($context, $userid, $filearea, $component)): the submissionid is assigned to userid
- Then in renderable.php, line 758, it assign the $sid (submission id) to $linkparams['userid']

So, the submissionid is assigned to userid and passed to the plagiarism plugin.
I'm sure that this error does not exist in Moodle 2.4 and 2.3

**Comment by tlock** [comment]
Hi Tri,

We do that so the files don't stay around forever and get cleaned up periodically.

If you have further fixes for the sesskey, feel free to do it and let know :)

I'd suggest creating a tracker item as looks like the same code in latest Moodle.

**Comment by dirkcgrunwald** [comment]
I'm curious about the suitability of this plugin for Moodle 2.8 or Moodle 2.9? It looks like it has the features we're looking for, but we have limited ability to forward-port and maintain code.

**Comment by thanhtri** [comment]
Hi dirkc,

I have installed it in Moodle 2.8 and it works fine. It has some known bug, which I fixed it on my local but haven't been commited to Git yet.

The current code, in my opinion, is quite messy now, which is quite hard to maintain. I have been working on a much cleaner code base, but it took much longer than I anticipate. So, currently, I only update this code to be compatible with new version of Moodle.

I haven't tested with Moodle 2.9 yet (but has it been released yet?)
(sorry for late response - I was sick)

**Comment by dirkcgrunwald** [comment]
Thank you for your response - I think I must have meant Moodle 2.8 (which
is what we're using)

If you're looking for collaborators or testers for your new 2.8+ plugin,
let me know.
We would also help better test the existing code for 2.8

**Pull request closed without merging**
